# Generated by Django 4.0.6 on 2022-07-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rake', '0003_alter_customer_state_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RakeArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrdate', models.DateField()),
                ('rrnumber', models.CharField(max_length=256)),
                ('receivingdate', models.DateField()),
                ('product_description', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bags_count', models.PositiveIntegerField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rake.category')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rake.customer', verbose_name='Customers')),
                ('receiving_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rake.branch')),
            ],
        ),
    ]
