# Generated by Django 4.0.6 on 2022-07-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rake', '0004_branch_rakearrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
